# Config file for train, eval and export params

# Dataset path
dataset:
  xnli: /Users/vietnd/Datasets/XNLI-1.0
  snli: /Users/vietnd/Datasets/SNLI

# cuda config:
cuda: false  # CPU

# Parameters
max_epochs: 10
train_bs: 64
test_bs: 64
lr_rate: 1e-5

# Saved model path
save_model_path: ${env:PWD}/tmp/models

# number of saved model
num_saved: 2

#
log_interval: 10




